# Generated by Django 5.0.3 on 2024-04-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('fam', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.TextField(max_length=50, verbose_name='Телефон')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
